import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../services/api";
import ActivityList from "../components/ActivityList";
import Icon from "../components/Icon";

export default function AdminPage() {
  const [data, setData] = useState({ summary: null, recentActivity: [] });
  const [error, setError] = useState("");
  useEffect(() => { api.get("/admin/summary").then((result) => setData(result)).catch((loadError) => setError(loadError.message)); }, []);
  const summary = data.summary || { users: 0, activeUsers: 0, boards: 0, tasks: 0, completed: 0, ongoing: 0, assigned: 0, pendingRequests: 0 };
  const completion = summary.tasks ? Math.round(summary.completed / summary.tasks * 100) : 0;
  return <section className="content-section admin-dashboard"><header className="page-heading"><div><span className="eyebrow">System administration</span><h2>PMS administration overview</h2><p>Monitor project work, account access, request queues, and platform activity from one protected control centre.</p></div><span className="admin-badge">Live system data</span></header>{error && <div className="form-alert">{error}</div>}<div className="dashboard-metrics admin-dashboard-metrics"><article><span className="metric-icon purple"><Icon name="team" /></span><div><small>Registered members</small><strong>{summary.users}</strong><span>{summary.activeUsers} active accounts</span></div></article><article><span className="metric-icon blue"><Icon name="board" /></span><div><small>Project boards</small><strong>{summary.boards}</strong><span>Active workspaces</span></div></article><article><span className="metric-icon orange"><Icon name="tasks" /></span><div><small>All tasks</small><strong>{summary.tasks}</strong><span>{summary.ongoing} ongoing</span></div></article><article><span className="metric-icon green"><Icon name="check" /></span><div><small>Completed</small><strong>{summary.completed}</strong><span>{completion}% completion rate</span></div></article><article className={summary.pendingRequests ? "warning" : ""}><span className="metric-icon red"><Icon name="request" /></span><div><small>Pending requests</small><strong>{summary.pendingRequests}</strong><span>Awaiting decision</span></div></article></div><div className="admin-overview-grid"><section className="panel admin-progress-card"><header><div><h3>Delivery overview</h3><p>Project-wide workflow totals</p></div><strong>{completion}%</strong></header><div className="admin-progress-visual"><div className="progress-ring large" style={{ "--progress": `${completion * 3.6}deg` }}><span>{completion}%</span></div><dl><div><dt>Assigned</dt><dd>{summary.assigned}</dd></div><div><dt>Ongoing</dt><dd>{summary.ongoing}</dd></div><div><dt>Done</dt><dd>{summary.completed}</dd></div></dl></div><div className="quick-admin-actions"><Link to="/admin/add-task"><Icon name="plus" />Add task</Link><Link to="/admin/members"><Icon name="team" />Members</Link><Link to="/admin/reports"><Icon name="reports" />Reports</Link><Link to="/admin/requests"><Icon name="request" />Requests</Link></div></section><section className="panel admin-activity-card"><header><div><h3>Recent platform activity</h3><p>Latest recorded board actions</p></div><span className="live-dot" /></header><ActivityList activities={data.recentActivity || []} compact /></section></div></section>;
}
